default:
  tags:
    - hb

variables:
  PACKAGE_NAME: php-class-generator

release:
  image: node:20
  before_script:
    - |
      curl -L --output /usr/local/bin/release-cli \
        "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
      chmod +x /usr/local/bin/release-cli
    - npm ci
  script:
    - npx vsce package --allow-missing-repository
    - VSIX_FILE=$(ls *.vsix)
    - echo "Uploading ${VSIX_FILE}"
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" \
           --upload-file "${VSIX_FILE}" \
           "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}/${VSIX_FILE}"
    - VSIX_URL="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${PACKAGE_NAME}/${CI_COMMIT_TAG}/${VSIX_FILE}"
    - echo "Download URL - ${VSIX_URL}"
    - |
      release-cli create --name "Release ${CI_COMMIT_TAG}" \
        --tag-name "${CI_COMMIT_TAG}" \
        --description "PHP Class Generator ${CI_COMMIT_TAG}" \
        --assets-link "{\"name\":\"${VSIX_FILE}\",\"url\":\"${VSIX_URL}\",\"link_type\":\"package\"}"
  artifacts:
    paths:
      - "*.vsix"
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
